---
- name: Converge
  hosts: all
  become: true

  vars:
    fs_dirs:
      - /tmp/fs-test-dir
    fs_copy:
      - dest: /tmp/fs-test-file.txt
        content: "Hello from Stouts.fs"
        mode: '0644'

  roles:
    - role: fs
